# Generated by Django 5.1.1 on 2024-09-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="coffe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(max_length=200)),
                ("value", models.FloatField(blank=True, max_length=5, null=True)),
                ("photo", models.ImageField(upload_to="", verbose_name="media/")),
            ],
        ),
    ]
